// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzvfqowqemdxvxmopffw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6dmZxb3dxZW1keHZ4bW9wZmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDg2NzQsImV4cCI6MjA3MTM4NDY3NH0.6tz5m272FfjIl8UIQT7YF2AQuORK88xUBwSq3MmEfBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});